# applies location and environment labels to cluster
kind: Cluster
apiVersion: clusterregistry.k8s.io/v1alpha1
metadata:
  name: frankfurt-dz
  labels:
    environment: prod
    location: frankfurt-dz